import { motion, type Variants } from "framer-motion";
import { CheckCircle, Shield } from "lucide-react";
import { useLanguage } from "@/context/LanguageContext";
const about2 = "/images/about-2.jpg";
const containerVariants: Variants = { hidden: { opacity: 0 }, visible: { opacity: 1, transition: { staggerChildren: 0.15, delayChildren: 0.1 } } };
const itemVariants: Variants = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 100, damping: 20 } } };
export default function About() {
  const { t, isRTL } = useLanguage();
  return <section id="about" className="py-24 md:py-32 bg-white relative overflow-hidden" dir="ltr"><div className="absolute top-0 right-0 w-[600px] h-[600px] bg-amber/10 rounded-full blur-[120px] translate-x-1/3 -translate-y-1/3" /><div className="container mx-auto px-4 md:px-6 relative"><div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center mb-20"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }} variants={containerVariants} className="max-w-xl"><motion.div variants={itemVariants} className="flex items-center space-x-4 mb-6"><div className="h-[2px] w-12 bg-amber" /><span className="font-display font-bold text-amber uppercase tracking-wider text-sm">{t.about.label}</span></motion.div><motion.h2 variants={itemVariants} className="font-display font-black text-4xl md:text-6xl text-navy-darker leading-[1.05] mb-6">{t.about.title1}<br /><span className="text-amber">{t.about.title2}</span></motion.h2><motion.p variants={itemVariants} className="font-sans text-gray-600 text-lg mb-8 leading-relaxed">{t.about.desc}</motion.p><motion.div variants={containerVariants} className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-10">{t.about.items.map((item) => <motion.div key={item} variants={itemVariants} className="flex items-center gap-3 bg-gray-50 border border-gray-100 rounded-lg p-4"><CheckCircle className="w-5 h-5 text-amber shrink-0" /><span className="font-display font-bold text-navy-darker text-sm">{item}</span></motion.div>)}</motion.div></motion.div><motion.div initial={{ opacity: 0, x: 50 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.8 }} className="relative"><div className="rounded-2xl overflow-hidden shadow-2xl"><img src={about2} alt="MKA Enerji Kurumsal" className="w-full h-[520px] object-cover" /></div><div className="absolute -left-6 -bottom-6 bg-[#031124] p-8 rounded-2xl shadow-2xl border-l-4 border-amber w-64"><div className="font-display font-black text-5xl text-amber mb-2">15+</div><div className="font-display font-bold text-white uppercase tracking-wider text-sm">{t.about.years}</div></div></motion.div></div><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{t.about.cards.map((item, idx) => <motion.div key={item[0]} initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: idx * 0.1 }} className="bg-gray-50 border border-gray-100 p-8 rounded-2xl hover:shadow-xl transition-all"><Shield className="w-12 h-12 text-amber mb-6" strokeWidth={1.5} /><h3 className="font-display font-black text-2xl text-navy-darker mb-4">{item[0]}</h3><p className="font-sans text-gray-600 leading-relaxed">{item[1]}</p></motion.div>)}</div></div></section>;
}
